AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - spec/dummy/db/**/*

Metrics/MethodLength:
  Max: 15

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*
